# Generated by Django 3.2.15 on 2022-11-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0044_courseenrollmentcelebration_celebrate_weekly_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='diet_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pmis_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ref_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.TextField(blank=True, null=True),
        ),
    ]
