# Generated by Django 3.2.15 on 2022-11-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0045_auto_20221107_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('government_school_teacher', 'Government School Teacher'), ('private_school_teacher', 'Private School Teacher'), ('principal', 'Principal'), ('teacher_trainee', 'Teacher Trainee'), ('teacher_trainer', 'Teacher Trainer'), ('cac', 'CAC'), ('crc', 'CRC'), ('brc', 'BRC'), ('jbt', 'Junior Basic Teacher'), ('tgt', 'Trained Graduate Teacher'), ('ht', 'Head Teacher'), ('diet_p', 'DIET Principal'), ('diet_f', 'DIET Faculty'), ('other', 'Other')], db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('CHGH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('PY', 'Pondicherry'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal')], db_index=True, max_length=6, null=True),
        ),
    ]
